import { SearchResponse } from "./types";

export const SAMPLE_PROPERTY = {
    address: "1450 Sample Ridge Road, Cedar Rapids, IA",
    latitude: 41.9779,
    longitude: -91.6656,
    date: "2024-05-21T12:00:00.000Z",
};

export function createSampleEvidence(): SearchResponse {
    const retrievedAt = "2024-05-23T15:30:00.000Z";
    return {
        schemaVersion: "2.1",
        generatedAt: retrievedAt,
        property: {
            latitude: SAMPLE_PROPERTY.latitude,
            longitude: SAMPLE_PROPERTY.longitude,
            timeZone: "America/Chicago",
            city: "Cedar Rapids",
            state: "IA",
            countyCode: "IAC113",
        },
        requestedLossDate: SAMPLE_PROPERTY.date,
        eventDayWindow: { start: "2024-05-21T05:00:00.000Z", end: "2024-05-22T05:00:00.000Z" },
        analysisWindow: { start: "2024-05-19T05:00:00.000Z", end: "2024-05-24T05:00:00.000Z" },
        precipitationContextWindow: { start: "2024-05-14T05:00:00.000Z", end: "2024-05-22T05:00:00.000Z" },
        records: {
            localStormReports: [
                {
                    id: "sample-lsr-hail",
                    category: "hail",
                    eventType: "Hail report",
                    classification: "reported",
                    startTime: "2024-05-21T22:14:00.000Z",
                    magnitude: { value: 1.25, unit: "in", qualifier: "measured" },
                    description: "A nearby public report described quarter-size hail. This is sample data for product demonstration.",
                    location: { latitude: 41.99, longitude: -91.62, distanceMilesFromProperty: 2.7, directionFromProperty: "NE" },
                    attributes: { reportSource: "Public", isSample: true },
                    source: { provider: "Iowa Environmental Mesonet", dataset: "NWS Local Storm Reports archive", productId: "SAMPLE-LSR-001", office: "DVN", sourceUrl: "https://mesonet.agron.iastate.edu/", retrievedAt },
                    quality: { status: "verified_format", flags: ["fictional_demo_record"] },
                    limitations: ["A report near the property does not establish conditions at the structure."],
                },
                {
                    id: "sample-lsr-wind",
                    category: "wind",
                    eventType: "Measured wind gust",
                    classification: "observed",
                    startTime: "2024-05-21T22:03:00.000Z",
                    magnitude: { value: 54, unit: "mph", qualifier: "measured" },
                    description: "An automated station measurement recovered through the Local Storm Report archive. This is sample data.",
                    location: { latitude: 41.94, longitude: -91.71, distanceMilesFromProperty: 3.5, directionFromProperty: "SW" },
                    attributes: { reportSource: "ASOS", accessPath: "local_storm_report_archive", isSample: true },
                    source: { provider: "Iowa Environmental Mesonet", dataset: "NWS Local Storm Reports archive", productId: "SAMPLE-LSR-002", office: "DVN", sourceUrl: "https://mesonet.agron.iastate.edu/", retrievedAt },
                    quality: { status: "verified_format", flags: ["fictional_demo_record"] },
                    limitations: ["A nearby station measurement may differ from conditions at the property."],
                },
            ],
            stationObservations: [
                {
                    id: "sample-station-wind",
                    category: "wind",
                    eventType: "Observed wind gust",
                    classification: "observed",
                    startTime: "2024-05-21T22:05:00.000Z",
                    magnitude: { value: 51.8, unit: "mph", qualifier: "measured" },
                    location: { latitude: 41.88, longitude: -91.71, distanceMilesFromProperty: 7.2, directionFromProperty: "S" },
                    attributes: { stationId: "KCID", isSample: true },
                    source: { provider: "Iowa Environmental Mesonet", dataset: "ASOS one-minute archive", recordId: "SAMPLE-KCID-001", sourceUrl: "https://mesonet.agron.iastate.edu/", retrievedAt },
                    quality: { status: "verified_format", flags: ["fictional_demo_record"] },
                    limitations: ["Station observations are measurements at the station, not the subject property."],
                },
            ],
            officialEvents: [],
            warnings: [
                {
                    id: "sample-warning",
                    category: "warning",
                    eventType: "Severe Thunderstorm Warning",
                    classification: "warning",
                    startTime: "2024-05-21T21:42:00.000Z",
                    endTime: "2024-05-21T22:30:00.000Z",
                    description: "The archived warning polygon includes the sample property point.",
                    location: { propertyInsideGeometry: true },
                    attributes: { isSample: true },
                    source: { provider: "National Weather Service", dataset: "Archived warning polygons", productId: "SAMPLE-WARN-001", office: "DVN", sourceUrl: "https://www.weather.gov/", retrievedAt },
                    quality: { status: "verified_format", flags: ["fictional_demo_record"] },
                    limitations: ["A warning describes a threatened area and is not a measurement at the property."],
                },
            ],
            radar: [],
            tropicalCyclones: [],
            disasters: [],
            imagery: [],
        },
        precipitation: {
            stationId: "KCID",
            stationName: "The Eastern Iowa Airport",
            distanceMilesFromProperty: 7.2,
            eventDayTotalInches: 0.82,
            prior24HoursInches: 0.84,
            prior72HoursInches: 1.16,
            priorSevenDaysInches: 2.04,
            maximumHourlyInches: 0.46,
            maximumThreeHourInches: 0.78,
            wetHourCount: 4,
            missingHourCount: 0,
        },
        imagery: {
            before: { itemId: "SAMPLE-S2-BEFORE", capturedAt: "2024-05-18T17:12:00.000Z", cloudCoverPercent: 8, sourceUrl: "https://dataspace.copernicus.eu/" },
            after: { itemId: "SAMPLE-S2-AFTER", capturedAt: "2024-05-23T17:10:00.000Z", cloudCoverPercent: 14, sourceUrl: "https://dataspace.copernicus.eu/" },
        },
        timeline: [
            { id: "sample-time-warning", recordId: "sample-warning", timestamp: "2024-05-21T21:42:00.000Z", endTime: "2024-05-21T22:30:00.000Z", title: "Severe Thunderstorm Warning included the property", explanation: "The property point falls inside the archived warning polygon.", classification: "warning", source: "National Weather Service archived warning", limitation: "A warning is not a property-level measurement." },
            { id: "sample-time-gust", recordId: "sample-station-wind", timestamp: "2024-05-21T22:05:00.000Z", title: "Nearby station recorded a 51.8 mph gust", explanation: "The KCID station recorded the maximum event-day gust returned in this sample.", classification: "observed", source: "KCID · ASOS one-minute archive", distanceMilesFromProperty: 7.2, magnitude: { value: 51.8, unit: "mph" } },
            { id: "sample-time-hail", recordId: "sample-lsr-hail", timestamp: "2024-05-21T22:14:00.000Z", title: "1.25 inch hail was reported nearby", explanation: "A Local Storm Report was recorded northeast of the sample property.", classification: "reported", source: "NWS Local Storm Reports archive", distanceMilesFromProperty: 2.7, magnitude: { value: 1.25, unit: "in" } },
        ],
        summary: {
            maximumObservedWindGustMph: 54,
            maximumObservedWindGustRecordId: "sample-lsr-wind",
            maximumReportedHailInches: 1.25,
            maximumReportedHailRecordId: "sample-lsr-hail",
            localStormReportCount: 2,
            warningCount: 1,
            officialEventCount: 0,
        },
        sources: [
            { id: "sample-source-station", provider: "Iowa Environmental Mesonet", dataset: "ASOS one-minute archive", status: "complete", recordCount: 1, retrievedAt, sourceUrl: "https://mesonet.agron.iastate.edu/", message: "Fictional formatted sample modeled on the production source shape.", limitations: ["Station conditions can differ from property conditions."] },
            { id: "sample-source-lsr", provider: "Iowa Environmental Mesonet", dataset: "NWS Local Storm Reports archive", status: "complete", recordCount: 2, retrievedAt, sourceUrl: "https://mesonet.agron.iastate.edu/", message: "Fictional formatted sample modeled on the production source shape.", limitations: ["Reports occur at reported locations and may be approximate."] },
            { id: "sample-source-warnings", provider: "National Weather Service", dataset: "Archived warning polygons", status: "complete", recordCount: 1, retrievedAt, sourceUrl: "https://www.weather.gov/", message: "Fictional formatted sample modeled on the production source shape.", limitations: ["Warning inclusion is not proof of conditions at a structure."] },
            { id: "sample-source-imagery", provider: "Copernicus Data Space Ecosystem", dataset: "Sentinel-2 imagery archive", status: "complete", recordCount: 2, retrievedAt, sourceUrl: "https://dataspace.copernicus.eu/", message: "Sample imagery availability metadata only.", limitations: ["Imagery is contextual and cannot establish roof-level damage."] },
        ],
        limitations: [
            "All records on this route are fictional sample data provided only to demonstrate report formatting.",
            "Nearby observations and reports do not establish conditions at the subject structure.",
            "Weather evidence does not determine physical damage, causation, insurance coverage, or claim outcome.",
        ],
        dataQualityWarnings: ["This is a fictional sample package and must not be used as a weather record."],
    };
}
