"use client";

import Link from "next/link";
import { useEffect } from "react";
import { ArrowRight, Building2, FileCheck2, Files, Plus, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDemoWorkspace } from "@/components/demo-workspace-provider";
import PackageStatus from "@/components/package-status";
import { packageEvidenceSummary, workspaceMetrics } from "@/lib/demo-workspace";
import { trackDemoEvent } from "@/lib/demo-analytics";

function LoadingWorkspace() {
    return <div role="status" className="rounded-2xl border border-brand-gray bg-white p-8 text-sm text-brand-olive/55">Loading the browser-local demo workspace…</div>;
}

export default function WorkspaceOverviewPage() {
    const { workspace, loading, storageError, resetWorkspace } = useDemoWorkspace();
    useEffect(() => trackDemoEvent("professional_workspace_opened"), []);
    if (loading) return <LoadingWorkspace />;
    if (!workspace) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6"><h1 className="text-xl font-semibold">Demo workspace unavailable</h1><p className="mt-2 text-sm text-red-800">{storageError}</p><Link href="/professionals" className="mt-5 inline-flex text-sm font-semibold underline">Return to professional overview</Link></div>;
    const metrics = workspaceMetrics(workspace);
    const recent = [...workspace.packages].sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)).slice(0, 5);
    return <div className="space-y-8">
        <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-olive/45">Demo Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Evidence workspace overview</h1><p className="mt-2 text-sm text-brand-olive/55">Fictional sample data and browser-local packages for repeated evidence preparation.</p></div><Link href="/professionals/workspace/packages/new" className="inline-flex h-11 items-center justify-center rounded-xl bg-brand-lime px-5 text-sm font-bold"><Plus className="mr-2 h-4 w-4" />New Evidence Package</Link></header>
        {storageError && <p role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">{storageError}</p>}
        <section aria-labelledby="organization-heading" className="flex flex-col gap-4 rounded-2xl border border-brand-gray bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-olive text-brand-lime"><Building2 className="h-5 w-5" /></span><div><h2 id="organization-heading" className="font-semibold">{workspace.organization.name}</h2><p className="mt-1 text-xs text-brand-olive/50">Fictional sample organization · {workspace.organization.type}</p></div></div><Link href="/professionals/workspace/organization" className="text-sm font-semibold underline underline-offset-4">Customize Demo Organization</Link></section>
        <section aria-labelledby="metrics-heading"><h2 id="metrics-heading" className="sr-only">Workspace metrics</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Draft packages", metrics.drafts, Files], ["Evidence ready", metrics.evidenceReady, FileCheck2], ["Report previews opened", metrics.reportsPreviewed, FileCheck2], ["Packages created this month", metrics.createdThisMonth, Plus]].map(([label, value, Icon]) => { const MetricIcon = Icon as typeof Files; return <article key={String(label)} className="rounded-2xl border border-brand-gray bg-white p-5"><MetricIcon className="h-4 w-4 text-brand-olive/55" /><p className="mt-5 text-xs text-brand-olive/50">{label as string}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{value as number}</p></article>; })}</div></section>
        <section aria-labelledby="recent-heading" className="rounded-2xl border border-brand-gray bg-white"><div className="flex items-center justify-between border-b border-brand-gray p-5"><div><h2 id="recent-heading" className="font-semibold">Recent packages</h2><p className="mt-1 text-xs text-brand-olive/50">Sample records are fictional and clearly labeled.</p></div><Link href="/professionals/workspace/packages" className="text-sm font-semibold">View all <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div>{recent.length ? <div className="divide-y divide-brand-gray">{recent.map((record) => <article key={record.id} className="grid gap-4 p-5 sm:grid-cols-[minmax(0,1.1fr)_minmax(0,1.3fr)_10rem_11rem] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{record.client.displayName || "Untitled client"}</p>{record.isSample && <span className="rounded-full bg-brand-lime/30 px-2 py-0.5 text-[9px] font-bold uppercase">Fictional sample</span>}</div><p className="mt-1 text-xs text-brand-olive/45">{packageEvidenceSummary(record)}</p></div><div><p className="text-sm text-brand-olive/70">{record.property.address || "Property not selected"}</p><p className="mt-1 text-xs text-brand-olive/45">{record.property.estimatedDateOfDamage ? new Date(record.property.estimatedDateOfDamage).toLocaleDateString() : "Date not selected"}</p></div><PackageStatus status={record.status} /><Link href={`/professionals/workspace/packages/${record.id}`} className="inline-flex h-9 items-center justify-center rounded-lg border border-brand-gray px-3 text-xs font-semibold">{record.status === "draft" ? "Continue Draft" : record.status === "evidence_ready" ? "Review Evidence" : "View Package"}</Link></article>)}</div> : <div className="p-10 text-center"><h3 className="font-semibold">Create your first client evidence package</h3><p className="mt-2 text-sm text-brand-olive/55">Add a client, property, and date of loss to begin reviewing available weather records.</p><Link href="/professionals/workspace/packages/new" className="mt-5 inline-flex h-10 items-center rounded-xl bg-brand-lime px-4 text-sm font-bold">New Evidence Package</Link></div>}</section>
        <div className="flex justify-end"><Button variant="outline" onClick={() => { if (window.confirm("Restore the original fictional organization and sample packages? Your browser-local demo changes will be removed.")) resetWorkspace(); }} className="border-brand-gray"><RotateCcw className="mr-2 h-4 w-4" />Reset Demo Workspace</Button></div>
    </div>;
}
